### PR TITLE
Reset player invincibility after restart and respect right boundary.

### PR DESCRIPTION
**Pull request by ericsmalling**
If player is "invincible" but dies (hits a small, yellow box), then upon game restart, the invicibility remains on until they hit another "Snyk monitor" sprite.

### CODE REVIEW

**Comment by ericsmalling** [comment]
This fixes part of issue #11

**Comment by ericsmalling** [comment]
@lirantal I wasn't sure if I should commit the files under `/dist` that `npm install` generates.  Let me know if you want me to do so.

**Comment by lirantal** [comment]
Right - you'd need to commit the changed files too. Can you push them?

**Comment by ericsmalling** [comment]
Sure - I have a fix for #18 too - will add both to this

**Comment by ericsmalling** [comment]
@lirantal okay I think it's all in. Plz test as I'm an npm noob!

**Comment by lirantal** [comment]
'k, taking a look

**Comment by lirantal** [comment]
Seems legit.

**Review by lirantal — COMMENTED** [review]
LGTM

**Pull request merged**
